theme = "chitin"
defaultContentLanguage = "de"

[Author]
    name = "Datenanfragen.de e. V."
    email = "kontakt@datenanfragen.de"

[languages]
    [languages.de]
        languageCode = "de-de"
        mollieLocale = "de_DE"
        languageName = "Deutsch"
        weight = 10
        title = "Datenanfragen.de e. V."
        copyright = "Dieses Werk ist unter einer Creative Commons Attribution-NoDerviatives 4.0 International-Lizenz lizensiert."
        baseURL = "https://verein.datenanfragen.de/"
    [languages.en]
        languageCode = "en-us"
        mollieLocale = "en_US"
        languageName = "English"
        weight = 20
        title = "Datenanfragen.de e. V."
        copyright = "This work is licensed under a Creative Commons Attribution-NoDerivatives 4.0 International License."
        baseURL = "https://verein.datenanfragen.de/en/"

[params]
    enableFooterTranslations = true
