[[languages.de.menu.topbar]]
    name = "Satzung"
    url = "/satzung"
    weight = 50
[[languages.de.menu.topbar]]
    name = "Spenden"
    url = "/spenden"
    weight = 10
[[languages.de.menu.topbar]]
    name = "Beitreten"
    url = "/mitglied-werden"
    weight = 20
[[languages.de.menu.topbar]]
    name = "Presse"
    url = "/press"
    weight = 30


[[languages.de.menu.footerleft]]
    name = "Unsere Ziele"
    url = "/mission-statement"
    weight = 10
# [[languages.de.menu.footerleft]]
#     name = "Artikel"
#     url = "/blog"
#     weight = 20
[[languages.de.menu.footerleft]]
    name = "Presse"
    url = "/press"
    weight = 30
    post = "<br>"
[[languages.de.menu.footerleft]]
    name = "Mitglied werden"
    url = "/mitglied-werden"
    weight = 40
[[languages.de.menu.footerleft]]
    name = "Spenden"
    url = "/spenden"
    weight = 50


[[languages.de.menu.footercenter]]
    name = "Satzung"
    url = "/satzung"
    weight = 10
[[languages.de.menu.footercenter]]
    name = "Gebührenordnung"
    url = "/gebuehrenordnung"
    weight = 30
[[languages.de.menu.footercenter]]
    name = "Vorstand"
    url = "/vorstand"
    weight = 40
[[languages.de.menu.footercenter]]
    name = "Transparenz"
    url = "/transparency"
    weight = 50


[[languages.de.menu.footerright]]
    name = "Impressum"
    url = "/contact"
    weight = 10
[[languages.de.menu.footerright]]
    name = "Datenschutzerklärung"
    url = "/datenschutz"
    weight = 20
[[languages.de.menu.footerright]]
    name = "<img src=\"/img/logo-itz.svg\" style=\"width: 100%; max-width: 300px; margin-top: 15px;\">"
    url = "/transparenz"
    weight = 30

# ----------------------------------------------------------------------------------------------------------------------

[[languages.en.menu.topbar]]
    name = "Constitution"
    url = "/constitution"
    weight = 50
[[languages.en.menu.topbar]]
    name = "Donate"
    url = "/donate"
    weight = 10
[[languages.en.menu.topbar]]
    name = "Become a member"
    url = "/become-a-member"
    weight = 20
[[languages.en.menu.topbar]]
    name = "Press"
    url = "/press"
    weight = 30


[[languages.en.menu.footerleft]]
    name = "Our goals"
    url = "/mission-statement"
    weight = 10
# [[languages.en.menu.footerleft]]
#     name = "Posts"
#     url = "/blog"
#     weight = 20
[[languages.en.menu.footerleft]]
    name = "Press"
    url = "/press"
    weight = 30
    post = "<br>"
[[languages.en.menu.footerleft]]
    name = "Become a member"
    url = "/become-a-member"
    weight = 40
[[languages.en.menu.footerleft]]
    name = "Donate"
    url = "/donate"
    weight = 50


[[languages.en.menu.footercenter]]
    name = "Constitution"
    url = "/constitution"
    weight = 10
[[languages.en.menu.footercenter]]
    name = "Membership fees"
    url = "/membership-fees"
    weight = 30
[[languages.en.menu.footercenter]]
    name = "Board"
    url = "/board"
    weight = 40
[[languages.en.menu.footercenter]]
    name = "Transparency"
    url = "/transparency"
    weight = 50


[[languages.en.menu.footerright]]
    name = "Legal notice and contact data"
    url = "/contact"
    weight = 10
[[languages.en.menu.footerright]]
    name = "Privacy policy"
    url = "/privacy"
    weight = 20
